### ISSUE TITLE
parse Error in ApiClient.php

### ISSUE THREAD

**Issue by timste** [Shirtigo/shirtigo-api-php#1]
there is an error in the ApiClient.php

PHP Parse error:  syntax error, unexpected '?' in /shirtigo-api-php-master/ApiClient.php on line 25

**Comment by tp-shirtigo** [comment]
Hello timste,
Thank you for your feedback. The mentioned line [1] contains a type hinting feature which is not available before php 7.1, see http://php.net/manual/en/migration71.new-features.php .

We will consider adding a version supporting php versions < 7.1 in the future. 
Please feel free to contact tech-support-at-shirtigo.de to let us know about your plans with our API!

* https://github.com/Shirtigo/shirtigo-api-php/blob/master/ApiClient.php#L25
