### ISSUE TITLE
undefined index: error on status 422

### ISSUE THREAD

**Issue by timohausmann** [Shirtigo/shirtigo-api-php#5]
Hey, I noticed a little irregularity in the error handling in ApiClient.php. 

Line 57 tries to access `$json['errors']` upon a status 422. This give me a `Notice: Undefined index: errors` which breaks the JSON response and the RuntimeException message (`Input validation failed: null`).

This happenes when posting a design file that is too small. The actual response looks liks this (it has a `message` but no `errors` property):

```
{
  "type":"UnprocessableEntityHttpException",
  "message":"The file 1167268692.png did not pass validation. ...",
  "status":422
}
```

https://github.com/Shirtigo/shirtigo-api-php/blob/6f7dc6b503f9b8067fda650bbe69e58fc5d1c1a5/ApiClient.php#L57

**Comment by chriskonnertz** [comment]
Hello @timohausmann,

thank you for reporting this issue, great feedback! :+1: 

We will investigate.
Might just be the wrong index, `$json['message']` instead of `$json['errors']`...

I will let you know as soon as this is fixed.

**Comment by chriskonnertz** [comment]
@timohausmann 

:arrow_right: https://github.com/Shirtigo/shirtigo-api-php/pull/7

**Comment by chriskonnertz** [comment]
Merged.

**Comment by timohausmann** [comment]
Great, thanks!
